### PR TITLE
Production-oriented installation facilities

### PR DESCRIPTION
**Pull request by silby**
Addresses #63; also part of a broader project to facilitate provisioning on the server side within our own environment which might or might not get used as a public example

### CODE REVIEW

**Comment by fluffy-critter** [comment]
I'm not sure how to actually use this right now. `vagrant provision` only wants to use `jshagam-dev` which already exists, and specifying an alternate name results in an error like

```
The machine with the name 'localverse' was not found configured for
this Vagrant environment.
```

**Comment by silby** [comment]
The branch as is doesn't work for me; did you test the freeform search? I get this error from trying to use it:

```
2019-07-29 12:02:51 [21524] [ERROR] Viroverse: obj(DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  operator does not exist: numeric[] ~~* unknown
LINE 1: ... ILIKE $3 OR me.sequence ILIKE $4 OR me.positions ILIKE $5 O...
```

**Comment by fluffy-critter** [comment]
Did you mean to post this on the other PR?

**Comment by silby** [comment]
Also, the facet consisting of all the discrete primer positions is probably only marginally useful, especially since sorting by name is asciibetical. If you can patch the facet code to replace "sort by name" with "sort by numeric value" when requested and make that the default sort for this facet, it'd be more useful since then someone could "browse" for an existing primer more easily. (Not the best UX for that but maybe good enough to help someone.)

**Comment by silby** [comment]
I'm suspending branch protection to merge the install branch while @fluffy-critter is away, because the change to how sqitch configuration works is somewhat disruptive and I don't want to develop other new stuff in parallel with it. This matter of storing VODA assays (#70) in Viroverse is a somewhat urgent request and I'm going to try to get it done. Most of the install branch is a no-op in production terms and testing by a non-me user went pretty well.

**Pull request merged**
